export const artistParams = {
  basic: {
    artist_name: 'string',
    date: 'date',
    start_time: 'string',
    end_time: 'string',
    type_of_show: 'string',
    pips_sent: 'boolean',
    specs_in: 'boolean',
    advance_contact: 'string',
    tour_manager_contact: 'string',
    production_manager_contact: 'string',
    arrival_on_site: 'string',
    load_in_time: 'string',
    sound_check_start: 'string',
    sound_check_end: 'string',
  },
  touring_crew: {
    front_of_house_engineer: 'boolean',
    monitor_engineer: 'boolean',
    lighting_designer: 'boolean',
    video_engineer: 'boolean',
  },
  stage: {
    touring_foh_desk: 'boolean',
    touring_monitor_desk: 'boolean',
    touring_lighting_desk: 'boolean',
    touring_video_desk: 'boolean',
    floor_package: 'boolean',
    touring_set: 'boolean',
    touring_sfx: 'boolean',
    backdrop: 'boolean',
    screen_use: 'boolean',
    source: 'boolean',
    follow_spot_use: 'boolean',
    department_requirements: 'string',
  },
  DJ: {
    djm_type: 'string',
    djm_quantity: 'number',
    cdj_type: 'string',
    cdj_quantity: 'number',
    '1210_type': 'string',
    '1210_quantity': 'number',
    dj_extras: 'string',
  },
  vehicles: {
    '28t_trucks': 'number',
    '18t_trucks': 'number',
    '7_5t_trucks': 'number',
    artic_trucks: 'number',
    tour_busses: 'number',
    bus_trailers: 'number',
    campervans: 'number',
    splitter_vans: 'number',
    vans: 'number',
    cars: 'number',
  }
};
